version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - full-ci-network

networks:
  full-ci-network:
    driver: bridge