name: Full CI Pipeline

on: [push, pull_request]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker services
        run: |
          docker compose up -d
          echo "Waiting for services to be healthy..."
          for i in {1..10}; do
            if curl -s http://localhost:5000/health; then
              echo "API is up!"
              break
            else
              echo "Waiting for API..."
              sleep 5
            fi
          done

      - name: Run SonarQube Scanner (SAST)
        run: |
          echo "Running SonarQube scan"
          # sonar-scanner ...

      - name: Run ZAP scan (DAST)
        run: |
          chmod -R 777 $(pwd)
          docker run --rm -v $(pwd):/zap/wrk/:rw \
            --user root \
            --network full-ci-network \
            zaproxy/zap-stable zap-baseline.py -t http://api:5000

      - name: Install Cypress dependencies
        run: |
          npm install
          npx wait-on http://localhost:5000/health

      - name: Run Cypress tests
        run: npx cypress run
