name: Full CI Pipeline

on: [push, pull_request]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker services
        run: |
          docker-compose up -d
          sleep 15

      - name: Run SonarQube Scanner (SAST)
        run: |
          echo "Running SonarQube scan"
          # sonar-scanner ...

      - name: Run ZAP scan (DAST)
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw ghcr.io/zaproxy/zap-baseline:stable -t http://host.docker.internal:5000
      - name: Install Cypress dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
