name: Full CI Pipeline

on: [push, pull_request]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run all services
        run: |
          docker-compose up -d
          sleep 15

      - name: Run SonarQube Scanner (SAST)
        run: |
          docker exec $(docker ps -qf "ancestor=sonarqube") echo "SonarQube Running"
          # In real case: Use sonar-scanner CLI or npm scanner here

      - name: Run ZAP scan (DAST)
        run: |
          docker run --network="host" owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000

      - name: Install Cypress dependencies
        run: npm install

      - name: Run Cypress tests (Functional)
        run: npx cypress run
