name: Full CI Pipeline

on: [push, pull_request]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker services
        run: |
          docker-compose up -d
          sleep 15  # Wait for services to be ready

      - name: Run SonarQube Scanner (SAST)
        run: |
          echo "Running SonarQube scan"
          # Example: sonar-scanner or another scanner command should be here
          # sonar-scanner -Dsonar.projectKey=your_project -Dsonar.sources=. -Dsonar.host.url=http://localhost:9000 -Dsonar.login=your_token

      - name: Run ZAP scan (DAST)
        run: |
          echo "Running ZAP scan"
          docker run --network="host" owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000

      - name: Install Cypress dependencies
        run: |
          npm install

      - name: Run Cypress tests (Functional)
        run: |
          npx cypress run
